# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db209dc4d4e86cb5b079539fdda6167f35c40335f26fd4e200bdb97f26a6d6b84c7c9a08205f739180d3139d1c8e52b8e6150f2f1872587f0b1faf8ee2113a69

test:
  secret_key_base: 2eac4889becde252f15534a4374e19e110b80defd2affd1a8cc88725e3c5b1d57f16ce8f1c3f75815742f2ea1a4672b49fc21eae26ceaff8064ea9e6e4de04ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
