# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b3994cff1921fa9bbd0d48b0f67396422dd13ab6f48a2e6656129a16c5db187748e3a511c21b1fae9f28c034f85135fe13c06e2bccb4334bb27b305a5d5c41

test:
  secret_key_base: aa58dd42130774916f44ec3d5fc819cda97b22a84b5a67aa87892160617c710872f8c862284052e0cac764e06b01417101cc013679df262faac0315685af364b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
