# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01c306f44eccaddddf49c5d8f4425edb1e7a9ec8f046100a981ea3dd423c855bddd1ee68d4c0510f5a332ca0b68193ac9d0338adebf6476d4451bbd7f0ff9f79

test:
  secret_key_base: f965ecc6fa425a46549b0f016c9bff29a9865594f502485482137b941634242aae674edd7332a78178193f719014e12ab2ae421e3cff88a4be428ab7e3b37f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
