# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c4cb3aea7d341961f3f2101269848917b8941b5759ee36b68edd2979086a139b824e2584bf72dda3351add4c56dbe74ed8d63e65c6124a9060b96f210c2c48

test:
  secret_key_base: fcf9715def119ba977059572b2e1b842d275bc85b57f4300d0a0d69f7104ec6df1c7d5f7039c68f0fae97aeeb99560753e29ea205f9f336be0e9962f6bea656e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
