# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1661db3c76d035fd57b886eb616359c5689c2cc7b30517d2bfe9a442fa49b28d643c16593898a846e2bd24d5bda96040e18e81cda67f447717ccdcf3a9025c2e

test:
  secret_key_base: 071cf81d8e660fcc066119e29f1b897d2a7265fddc900edcf8bec2460f447dccf79645d3a5d0111ae2ea430162a2858e5dc03c6b2a738c51513083f1b8165d84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
