# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551f8f332604f7aee4bfd33e71f4cc15bc9a9eb9a84daf891c4889901e30b516d1c36e4026c14f47db3b1c58f77698cb86c5d85d28730346140c7fec6eaa453d

test:
  secret_key_base: 343bfa2f3b994ccc22f394b2949d1b5cbe912123524997cedf03be53139e9460d7072e6c88c8e0ea90a47678860991420dc3f5d7b57f7a498d6b958b6880f3e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
